### ISSUE TITLE
Properties are convered to type String when moving multiple messages at once

### ISSUE THREAD

**Issue by elendis** [jmstoolbox/jmstoolbox#102]
## Specifications
- JMSToolBox version: 5.8.0
- OS (Name, version, 32/64bits): Windows 10, 64bit
- Q provider (kind, version) : ActiveMQ 5.15.5

## Expected Behavior
When moving multiple messages containing a property of i.e. type Double, the property should keep its type.

## Actual Behavior
The properties are converted to type String.

## Steps to Reproduce the Problem

1. Send multiple new message to QueueA with a property of type Double
2. Move all messages to QueueB (via mouse drag & drop) at once (multi-select)
3. Check property types of messages in QueueB => it's String.

The headers are kept when moving one message at a time, the issue only occurs when moving multiple messages at the same time.

**Comment by titou10titou10** [comment]
This issue arise whenever a message is "copied", not only with multiple selection or copied to a different destination

**Comment by elendis** [comment]
Thank you 👍
