### ISSUE TITLE
Message payload display stops on first null character

### ISSUE THREAD

**Issue by MocniMax** [jmstoolbox/jmstoolbox#111]
## Specifications
- JMSToolBox version: 5.10.0
- OS (Name, version, 32/64bits): Windows server 2019
- Q provider (kind, version) : IBM MQ 9.2

## Expected Behavior
Each message no matter which characters it contains, should be always displayed in full length. The Payload length is shown correctly.

## Actual Behavior
Only message part up to first null character is displayed. I expected the same behavior with any other non printable character.

## Steps to Reproduce the Problem

  1. Post message with null character in it
  2. Display it in Payload tab or  View Message Payload tab
  3. While length is correctly shown, message itself is not

**Comment by titou10titou10** [comment]
What is the JMS type of the message?

**Comment by MocniMax** [comment]
A plain Text one, nothing special. Here is its screenshot:

![image](https://user-images.githubusercontent.com/26117076/115774459-e2877880-a3b1-11eb-85ff-f81d97f2770a.png)

It is completely visible in IBM MQ Explorer:

![image](https://user-images.githubusercontent.com/26117076/115774577-0f3b9000-a3b2-11eb-8036-6bc6e8685558.png)

As you can see, message length is 62 bytes what is correctly displayed.

**Comment by titou10titou10** [comment]
heu... The "messaqe text" box in MQ explorer shows the same thing as in JTB... 

MQE also shows the binary representation of the content in the "Message data bytes"... JTB only shows a binary representation of the payload for`"BytesMessage"`, not for"`TextMessage"` as in your case

JTB and MQE diplay the result of "`TextMessages.getText()"`that returns a `"String"` and x'00' is not a displayable character
If the message type was`"bytes"`you would see the binary representation of the payload, in the same way MQE does
So JTB works as it should. 

What you want is a binary display for the payload of`"TextMessage"`. This is a feature request..

And IMHO, I don't think it is a good practice to set binary data in the payload of a`"TextMessage"`but you probably have a good use case for that

**Comment by MocniMax** [comment]
Must to disagree. A null character is not an binary value, it is a null value. There are common character definitions of LOWVALUE (\0) and HIGHVALUE (\f) for character/value boundaries and area initializations. Both are just in the area of non printable characters, not binary values.

The string representation you are talking about is C and Java related or, to be precise, is C and Java string manipulation related. If you use some other language to process queue data (COBOL for instance), complete data up to defined length is available all the time. Using character area approach instead of string one will give same result in C and Java. Therefore each queue message has its length as control value so receiver can fetch it in its full length.

Anyway, any of them has nothing to do with actual data passed to the queue. There is no limitation in characters that can be in message and passed to the queue, otherwise queue communication between different platforms will not be possible. I am working on different platforms with different CPU technologies (x64, POWER9, IBM Mainframe) using the same programming languages (C/C++, COBOL, Java) and IBM MQ to exchange data between them. Two completely different character encodings are on them, the ASCII and EBCDIC and, thanks to the IBM MQ, data are exchanged between them with no issues.

And null characters are always a valid and, on some platforms, recommended for defining not delivered values because a null character is not an value while blank and zero for numbers are. When you have nulls in message then you are absolutely sure that data is not delivered.  

It will be really nice and very useful if JTB can display complete message no matter which type it is especially when it can export such message/payload with no issues.

**Comment by titou10titou10** [comment]
Feature request created: #114
