### ISSUE TITLE
When showing Apache Active MQ queues, all queue "Depth" values are "N/A".

### ISSUE THREAD

**Issue by JavaJeffG** [jmstoolbox/jmstoolbox#116]
## Specifications
- JMSToolBox version: v5.11.0
- OS (Name, version, 32/64bits): Windows
- Q provider (kind, version) : Apache Active MQ

## Expected Behavior
   After clicking "Show Queues Depth" the Queues depth window should list queue names and corresponding Depth values.

## Actual Behavior
   After clicking "Show Queues Depth" the Queues depth window shows a list of queue names and all Depth values are "N/A".

## Steps to Reproduce the Problem

  1.  Connect to an Apache Active MQ broker running in AWS.
  1.  Right click on "Show Queues Depth"
  1.  The Queue depth window pops-up and says "(Refreshing...)"
  2.  When finished refreshing the queue names are listed, there is a value in the "JMS Timestamp of 1st Message" column for non-empty queues, but the Depth for all queues is "N/A".

## Logs
Eventually, attach the log files which are `"<user>\.jtb\JMSToolBox\jmstoolbox.log"` and `"<user>\.jtb\.metadata\.log"`    
They can be exported directly from JMStoolBox: Menu "Help" > "Export JMSToolBox log files..."

**Comment by titou10titou10** [comment]
Strange...
It works on my test workstation for me with Active MQ v5.16.1 and v5.10.2 ...
Do you have some kind of messages in the logs?

**Comment by titou10titou10** [comment]
@JavaJeffG you are right. The !queue depth" feature only works for ActiveMQ when connected via JMX as the value is retrieved via an exposed MBean...
An alternative would be to browse+count the messages on each Q which may be very resource intensive if many Q with tons of messages are present
This behavior will not be changed in JTB. sorry
