### ISSUE TITLE
Edit message on Drag'n'Drop

### ISSUE THREAD

**Issue by blackfoxoh** [jmstoolbox/jmstoolbox#12]
## Expected Behavior
allow the message to be edited when drag'n'drop a single message from one queue to another (like it does when d'n'd from the templates. Maybe use 'Ctrl' keyboard modifier to do so and leave the default behaviour as is.
This would be very handy when it comes to testing, having one message in a queue somewhere which needs to be resend slightly modified (headers, payload) to test different usecases.

Demarcation: When d'n'd more than one message at once don't show an edit-dialog (behaviour as it is now).

My first choice would be the above mentioned decission per usecase by holding ctrl-key pressed or not while d'n'd. 
Alternative a preference to choose the behaviour might be ok as well.

What do you think?
Ralf

**Comment by titou10titou10** [comment]
The message editor is now presented to the user when D&D is used for one ,message

**Comment by blackfoxoh** [comment]
thank you very much
