### ISSUE TITLE
Message placed in new created queue without prefix jms.queue

### ISSUE THREAD

**Issue by fnoorden** [jmstoolbox/jmstoolbox#123]
## Specifications
- JMSToolBox version: 5.11.0
- OS (Name, version, 32/64bits): Windows 10 64bits
- Q provider (kind, version) : Red Hat AMQ 7.8.1 (Artemis 2)

## Expected Behavior
When I send a message to a queue named jms.queue.healthqueue, the message should be placed in the jms.queue.healthqueue

## Actual Behavior
When I send a message to a queue named jms.queue.healthQueue, then a new queue with the name healthQueue is created and the message is placed in the healthQueue (no jms.queue prefix). The message will not appear in jms.queue.healthQueue.

## Steps to Reproduce the Problem

  1. right-click on jms.queue.healthQueue
  2. send a message
  3. disconnent
  4. connect
  5. A new queue is created named healthQueue (without jms.queue)
  6. the message is present in the new queue
  7. the message not present in the jms.queue.healthQueue

## Logs
Attached
[JTB_20213518_1711457_jmstoolbox.log](https://github.com/jmstoolbox/jmstoolbox/files/7564432/JTB_20213518_1711457_jmstoolbox.log)
[JTB_20213518_1711457_eclipse.log](https://github.com/jmstoolbox/jmstoolbox/files/7564433/JTB_20213518_1711457_eclipse.log)

**Comment by titou10titou10** [comment]
What do you mean by "A new queue is created named healthQueue (without jms.queue)" ? Is it a temporary queue?
JMSToolBox does not create Queues...
IMHO it seems this is a behavior related to Artemis configuration

**Comment by titou10titou10** [comment]
Closed for lack of information, Please reopen if this is still pertinent
