### ISSUE TITLE
Wiki update suggestion

### ISSUE THREAD

**Issue by johnsgp** [jmstoolbox/jmstoolbox#128]
Is it possible to make contributions to the Wiki?
I would like to suggest a change to https://github.com/jmstoolbox/jmstoolbox/wiki/1.1-Quick-Start
Changing
```
Unzip the dowladed package somewhere
```
to
```
Unzip the package, downloaded from https://github.com/jmstoolbox/jmstoolbox/releases, to a directory of your choice
```

**Comment by titou10titou10** [comment]
Done.
Thanks for your input!
