### ISSUE TITLE
Connect unsuccessful

### ISSUE THREAD

**Issue by marko-lazic** [jmstoolbox/jmstoolbox#129]
## Specifications
- JMSToolBox version: 5.12.0 gtk linux
- OS (Name, version, 32/64bits): Ubuntu 21.10
- Q provider (kind, version) : Payara embeded OpenMQ, inside vagrant virtualbox port forwarded 7676 -> 7777

## Expected Behavior
Should connect to the embeded OpenMQ server

## Actual Behavior
Internal Error
Connect unsuccessful

Reason:
java.net.UnknownHostException: vbox

Details:
vbox

## Steps to Reproduce the Problem

  1. Follow the instructions on [this blog](http://ryukocndevjava.blogspot.com/2018/07/glassfish-412-java-ee-functionalities.html) to configure payara and jmstoolbox
  2. 

## Logs
2022-01-18T10:39:32.998+0000] [Payara 5.2021.7] [INFO] [AS-JMS-CORE-00001] [javax.enterprise.resource.jms] [tid: _ThreadID=144 _ThreadName=JMS_PROXY_default_JMS_host-kernel(1) SelectorRunner] [timeMillis: 1642502372998] [levelValue: 800] [[
  JMS Service Connection URL is : mq://localhost:7676/]]

## Alternative try
I tried running jmstoolbox and payara locally and I got same error.

**Comment by titou10titou10** [comment]
Please reopen with the requested info if you still get the problem with the latest version of JMSToolBox
