### ISSUE TITLE
IBM MQ "JMSXAppID" not overridden by the "Client ID" string  set in preferences

### ISSUE THREAD

**Issue by lnazo** [jmstoolbox/jmstoolbox#134]
## Specifications
- JMSToolBox version: 5.13.0
- OS (Name, version, 32/64bits): Windows 10 64bit
- Q provider (kind, version) : IBM MQ

## Expected Behavior
Would it be possible to add a feature to specify the JMSXAppID over IBM MQ? Currently the default is set to JMSToolBox

## Actual Behavior
Provide a way of setting a custom JMSXAppID value

## Steps to Reproduce the Problem
1. Browse a queue
2. Select a message that was originally sent using JMSToolBox
3. The JMSXAppID is set to JMSToolBox

## Logs
N/A

**Comment by titou10titou10** [comment]
This can be configured in the preferences:
File > Preferences> General > Connection > "JMS connection Client ID prefix"

**Comment by lnazo** [comment]
Hi, I gave it a try but it still remains as "JMSToolBox"
