### ISSUE TITLE
Setting JMS message object properties via IBM MQMD

### ISSUE THREAD

**Issue by lnazo** [jmstoolbox/jmstoolbox#135]
## Specifications
- JMSToolBox version: 5.13.0
- OS (Name, version, 32/64bits): Windows 10 64bit
- Q provider (kind, version) : IBM MQ

## Expected Behavior
Is it possible to set the MQMD fields via message object properties prefixed JMS_IBM_MQMD e.g. JMS_IBM_MQMD_ApplIdentityData using JMSToolBox?

## Actual Behavior
Provide way to set MQMD fields

## Steps to Reproduce the Problem

  1. Browse a queue
  2. Select send message
  3. Set JMS_IBM_MQMD message object properties

## Logs
N/A

**Comment by titou10titou10** [comment]
With the yet unpublished version of JTB, yes you can add JMS properties starting with "JMS_" (thanks to #133)
That includes proprietary properties for IBM MQ (starting with "JMS_IBM_")

**Comment by titou10titou10** [comment]
Please reopen if you still get the problem with the latest version of JMSToolBox
