### ISSUE TITLE
Solace session doesn't list all the queues 

### ISSUE THREAD

**Issue by NandiniVB** [jmstoolbox/jmstoolbox#139]
## Specifications
- JMSToolBox version: v5.10.0
- OS (Windows10, 64bits):
- Q provider (kind, version) : Solace

## Expected Behavior
List all the queues from my solace service

## Actual Behavior
doesn't list all the queues, only handful of queues are listed in JMS tool box

## Steps to Reproduce the Problem

  1. Open a session configured for Solace
  2. View existing queues under the session
[JTB_20223125_1307349_jmstoolbox.log](https://github.com/jmstoolbox/jmstoolbox/files/9177805/JTB_20223125_1307349_jmstoolbox.log)

## Logs
[JTB_20223125_1307349_jmstoolbox.log](https://github.com/jmstoolbox/jmstoolbox/files/9177802/JTB_20223125_1307349_jmstoolbox.log)

**Comment by titou10titou10** [comment]
Could you be more precise about the problem?

- What queues are not listed? 
- do you see a pattern in the name or characteristics of the missing queues?
- are missing queues listed in the log you joined to this ticket?

**Comment by titou10titou10** [comment]
Closed for lack of information, Please reopen if this is still pertinent
