### ISSUE TITLE
Add "use as selector" to contextmenu in messagelist

### ISSUE THREAD

**Issue by blackfoxoh** [jmstoolbox/jmstoolbox#14]
## Specifications
- JMSToolBox version: latest

## Expected Behavior
display the content of a queue, maybe with a custom columns set. When doing a right-click (show contextmenu) on a message: add the option "use as selector" (and "build selector" for timestamps) for the column on which the mouseclick has been done. When the contextmenu is displayed by keyboard and therefore there is no column specified by clickposition I would suggest to display the options for "JMS Timestamp" which is available on every message.
This would save lots of time not having to navigate to appropriate "JMS headers" or "Properties" tab in the message details view, especially when payloadview is the default to display.

**Comment by blackfoxoh** [comment]
Hi Denis,
looks really great and your implementation with the different choices is even more sophisticated I would have expected :-)
Thank you very much!

**Comment by titou10titou10** [comment]
Thanks
It has been inspired from DBeaver where I am the author of the DB2 plugin
