### ISSUE TITLE
JMSToolBox accesses System Queue on connection (IBM MQ)

### ISSUE THREAD

**Issue by weberjn** [jmstoolbox/jmstoolbox#145]
## Specifications
- JMSToolBox version: 6.0.0
- OS (Name, version, 32/64bits): Win11
- Q provider (kind, version) : IBM MQ

I get 2035 MQRC_NOT_AUTHORIZED on connecting.

Sysadmin says this is because I want to access SYSTEM.COMMAND.INPUT

Can you configure JMSToolBox to not do this?

**Comment by titou10titou10** [comment]
unfortunately no
With MQ, JTB  uses the MQ "Administrative Command channel"  and PCF (Programmable command format) for many tasks, like getting the list of queues and topics, retrieve destination information etc.
The JMS API does not standardize nor request implementors to provide API for administration like the JDBC specs do

**Comment by weberjn** [comment]
I guess few MQ admins give you admin rights.
What about an admin-less JMSToolBox mode where you have to enter queue names yourself, as with Hermes JMS ? Hermes works without admin rights.

**Comment by weberjn** [comment]
HermesJMS is no longer being supported and does not work post Java 8, so we are looking for an alternative.
