### ISSUE TITLE
Unable to add http support to activemq QManager

### ISSUE THREAD

**Issue by chrisw-alfa** [jmstoolbox/jmstoolbox#149]
## Specifications
- JMSToolBox version: 6.1
- OS (Name, version, 32/64bits): 64
- Q provider (kind, version) : ApacheMQ, org.titou10.jtb.qm.activemq_1.0.0.202303161239

## Expected Behavior
One can add apache http-transport to Q manager and then use JMS over http - therefore connecting to a broker over http

## Actual Behavior
`java.lang.ClassNotFoundException: org.apache.activemq.transport.TransportFactory cannot be found by org.titou10.jtb.qm.activemq.resource_1.0.0
org.apache.activemq.transport.TransportFactory cannot be found by org.titou10.jtb.qm.activemq.resource_1.0.0
`

## Steps to Reproduce the Problem

  1. Add activemq-http jar to Q manager (I tried with same version as what is used in the titou package)
  2. Attempt to connect to host
  3. sad times

## Logs
  _[DF] I removed the stack trace as it is not relevant, just showing you not have IBM MQ jars setup_

[JTB_20233217_100521_eclipse.log](https://github.com/jmstoolbox/jmstoolbox/files/11496437/JTB_20233217_100521_eclipse.log)
[JTB_20233217_100521_jmstoolbox.log](https://github.com/jmstoolbox/jmstoolbox/files/11496438/JTB_20233217_100521_jmstoolbox.log)

**Comment by titou10titou10** [comment]
The exception you receive is "normal" ass the jard added in the configuration page on JTB are in a different ClassLoader. This is part of the complexity of the Eclipse-RCP/OSGI platform
What has to bee done is to add the`activemq-http`jar directly in JTB. I will do that now
A solution that *may* work, is to add to the configuration, ***all*** the jar already bundled with jtb: active-mq-client, activemq-openwire-legacy, geronimo-j2ee-management_1.1_spec, hawtbuf in addition to activemq-http

**Comment by chrisw-alfa** [comment]
Hey @titou10titou10,

Thanks for the response;

Testing out your workaround, after adding all the modules, I see a slightly different error:

`java.lang.ClassNotFoundException: org.slf4j.LoggerFactory cannot be found by org.titou10.jtb.qm.activemq.resource_1.0.0
org.slf4j.LoggerFactory cannot be found by org.titou10.jtb.qm.activemq.resource_1.0.0`

(going to test if adding that jar helps too)

**Comment by titou10titou10** [comment]
I commited the code in JTB that will make it work so now you can build JTB by yourself, or wait until I publixh v6.2.

As for the jars, I discovered that more jars are required but as said I'm not sure it will wait:

Check https://github.com/jmstoolbox/jmstoolbox/blob/dev/org.titou10.jtb.qm.activemq/build.properties

Also on my setup, port 8161 is for the console, nor for JMS over HTTP. The port to use is the one defined in the`transportConnector`stanza of your server:

    <transportConnectors>
        <transportConnector name="http" uri="http://0.0.0.0:8080" />
    </transportConnectors>

With`brokerURL=http://0.0.0.0:8080`

**Comment by chrisw-alfa** [comment]
Thanks @titou10titou10,

Do you have a date for the release yet?

Cheers

**Comment by titou10titou10** [comment]
done
