### ISSUE TITLE
“JMSToolBox” is damaged and can’t be opened. You should move it to the Bin.

### ISSUE THREAD

**Issue by MujtabaZAGhauri** [jmstoolbox/jmstoolbox#150]
I've had an issue when trying to install JMS toolbox on my MAC. I've followed the wiki but get the above error mentioned in the title. My OS is Venure 13.0
![Screenshot 2023-08-14 at 12 25 46](https://github.com/jmstoolbox/jmstoolbox/assets/52796130/305750e4-cfc0-4def-95d3-343f33096e3b)

**Comment by titou10titou10** [comment]
this is the first time this is reported and as I don not have the hardware to test, I do not know what's happening here

did you download the correct version for your system: x56_64 vs aarch64?

If you google "mac app is damaged and can't be opened you should move it to the" you'll find many answer to the problem
Maybe apply the solution at point 4. there https://osxdaily.com/2019/02/13/fix-app-damaged-cant-be-opened-trash-error-mac/ and see if it works?

**Comment by jordidg** [comment]
I can confirm the error (both on x86_64 and aarch64)
Removing the com.apple.quarantine extended atttribute fixes it:
`xattr -d -r com.apple.quarantine /Path/to/application/`

**Comment by titou10titou10** [comment]
thanks @jordidg . I've updated the README file with this instruction when installing JTB

https://github.com/jmstoolbox/jmstoolbox/blob/dev/README.md

**Comment by MujtabaZAGhauri** [comment]
Thats worked!! Thanks everyone for your help!
