### ISSUE TITLE
REST: add the possibility to select messages via a JMS selector when deleting message

### ISSUE THREAD

**Issue by etkinator** [jmstoolbox/jmstoolbox#152]
## Specifications
- JMSToolBox version:
- OS (Name, version, 32/64bits):
- Q provider (kind, version) :

## Expected Behavior
filtered messages are deleted

## Actual Behavior
FIrst N messages are deleted. I dont know how to filter mesages to consume. MessageInput has no affect to which messages a consumed.

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Logs
Eventually, attach the log files which are `"<user>\.jtb\JMSToolBox\jmstoolbox.log"` and `"<user>\.jtb\.metadata\.log"`    
They can be exported directly from JMStoolBox: Menu "Help" > "Export JMSToolBox log files..."

**Comment by titou10titou10** [comment]
ok. What's the problem here?

**Comment by etkinator** [comment]
Unable to delete specific messages

**Comment by titou10titou10** [comment]
> Unable to delete specific messages

indeed. this is not implemented. 
What are you looking for exactly? 
please explain "specific messages"

**Comment by etkinator** [comment]
Messages to queue a writed by multiple threeds and I need delete mesage with specific custom properties. I need use jmsSelector.

**Comment by etkinator** [comment]
Can you send me new win version, supporting this feature, please?
