### ISSUE TITLE
Unable to connect to SoftwareAG Universal Messaging server

### ISSUE THREAD

**Issue by enowaksag** [jmstoolbox/jmstoolbox#153]
## Specifications
- JMSToolBox version: 6.2.0
- OS (Name, version, 32/64bits):  Windows 10/64 bit
- Q provider (kind, version) : SoftwareAG Universal Messaging version 10.15

## Expected Behavior
Should be able to connect to the SoftwareAG Universal Messaging server.

## Actual Behavior
When connecting to the SoftwareAG Universal Messaging version 10.15 -- getting the error message:
java.lang.ClassNotFoundException: com.pcbsys.nirvana.client.nSessionAttributes cannot be found by org.titou10.jtb.qm.um_1.0.0.202305181821

## Steps to Reproduce the Problem

  1.  Copied the nAdmin.jar, nJMS.jar, and nClient.jar file from the <installdir>\UniversalMessaing\lib directory to the JMSToolBox/plugins directory.  Note, the nClient.jar file contains the nSessionAttributes as mentioned in the error.
  2.  Started JMSToolBox and created a new session  by configuring a NSP connection to the Universal Messaging server.  IN this case, Universal Messaging Server and JMSToolBox are on the same Windows VM so there is no firewall rule issue.
  3.  Click on the session to connect -- and the error message is displayed.
  
  Attaching the log files..

## Logs
Eventually, attach the log files which are `"<user>\.jtb\JMSToolBox\jmstoolbox.log"` and `"<user>\.jtb\.metadata\.log"`    
They can be exported directly from JMStoolBox: Menu "Help" > "Export JMSToolBox log files..."
[JTB_20235311_1609506_jmstoolbox.log](https://github.com/jmstoolbox/jmstoolbox/files/12580316/JTB_20235311_1609506_jmstoolbox.log)
[JTB_20235311_1609506_eclipse.log](https://github.com/jmstoolbox/jmstoolbox/files/12580317/JTB_20235311_1609506_eclipse.log)

**Comment by titou10titou10** [comment]
Please follow the instruction on how to add proprietary jars for your QM
The jars must not be copied anywhere but with the JTB interface, you have to add them to the application
Doc: https://github.com/jmstoolbox/jmstoolbox#configuring-a-queue-provider

**Comment by enowaksag** [comment]
OMG!  What a freakin' idiot I am -- completely glossed over that section.  Yes - I'm now able to connect to SoftwareAG Universal Messaging Server version 10.7 and 10.7 -- Having issue with 10.11 but am researching.
