### ISSUE TITLE
Question about System Variables in Templates 

### ISSUE THREAD

**Issue by jtrillos** [jmstoolbox/jmstoolbox#155]
## Specifications
- JMSToolBox version: 6.3.0
- OS (Name, version, 32/64bits): Windows 10 64bits

## Question
In the wiki said that we can use system variables in the templates. However, I do not know how to use the attributes for the variables. For example, ${currentTime} with an offset. 

Can someone please explain me, how can I do it? And if this is possible some examples would be nice

Thank you

**Comment by titou10titou10** [comment]
What is your need exactly? to have a variable that will contain, let say, "currentTime" + 2 hours?
For this you need to create a custom variable of type "Date/Offset" and use it in your templates

**Comment by jtrillos** [comment]
Yes, exactly. 

Could you please update the wiki with this information? At least that said what you already explain. 

Thank you.
