### ISSUE TITLE
Cannot invoke "javax.jms.Message.getJMSTimestamp()" because "firstMessage" is null

### ISSUE THREAD

**Issue by lancechant** [jmstoolbox/jmstoolbox#163]
## Specifications
- JMSToolBox version: 6.4.0
- OS (Name, version, 32/64bits): 64
- Q provider (kind, version) : activemq

## Expected Behavior
Be able to browse queue depth

## Actual Behavior
Page is stuck on refreshing, and nothing happens, logs show an exception because of null

## Steps to Reproduce the Problem

  1. Connect to the queue
  1. Right click Queues and select show queue depth

## Logs
`!ENTRY org.eclipse.core.jobs 4 2 2024-03-05 11:09:38.313
!MESSAGE An internal error occurred during: "Collect Queue Depth job for Local".
!STACK 0
java.lang.NullPointerException: Cannot invoke "javax.jms.Message.getJMSTimestamp()" because "firstMessage" is null
	at org.titou10.jtb.jms.model.JTBConnection.getFirstMessageTimestamp(JTBConnection.java:659)
	at org.titou10.jtb.ui.part.content.CollectQueueDepthJob.run(CollectQueueDepthJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
`

**Comment by lancechant** [comment]
We using 5.18.3 for the active MQ version.

I added the metaData log to the issue, the other had a lot of information, so will have to try reproduce with the limited data set, if I can manage it again.

It is yeah, because those timestamps when looking at the activeMQ UI were present and accounted for, so not entirely sure why that error came about. If I can reproduce it again I will give more information.. But this was on our POISON queue I found out, which can me any multitude of malformed messages, and could even be some messages that aren't JMS to begin with.

So I am not sure if I can reproduce it again, but if I can I will update @titou10titou10

**Comment by titou10titou10** [comment]
I think the logs are need to debug. 
What I understand is that the problem occurred once, is that right?
as a workaround if the problem, you can add a filter to exclude the failing queue

**Comment by lancechant** [comment]
I will try provide the other log file if I get it to happen again.

This is around the third time I have noticed it, but the first time I investigated it as had the time to.
The thing is I didn't know what queue was failing to begin with, as there were a few queues I was testing with.. maybe as a start the error could say where it's originating from?

But it is interesting that they don't fail on the active MQ UI, and have everything populated there, but not being picked up by JMS toolbox

**Comment by titou10titou10** [comment]
The exception occurs here with`firstMessage`being null (My previous comment was not on the spot..): 

https://github.com/jmstoolbox/jmstoolbox/blob/b47a05f1122b94488a76e1ff77aff78a6bf872de/org.titou10.jtb.core/src/org/titou10/jtb/jms/model/JTBConnection.java#L656-L660

What bugs me is that `Enumeration.nextElement()` can not return null... In case there is no element, it must throw a`NoSuchElementException`exception. I can not figure how `"firstMessage"` can be null here.: https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Enumeration.html

It may be a bug in the activemq client implementation


After checking the code here: https://github.com/apache/activemq/blob/cd5c993eed4e31edd0e6715b431e068889ccaab3/activemq-client/src/main/java/org/apache/activemq/ActiveMQQueueBrowser.java,  it is indeed a bad implementation of the`Enumeration`interface. 
There are many places where the`Enumeration.nextElement()`method can return null...

    public class ActiveMQQueueBrowser implements QueueBrowser, Enumeration {
    ... 
    public Object nextElement() {
        while (true) {

            synchronized (this) {
                if (consumer == null) {
                    return null;
                }
            }

I'll add a defensive test in JTB to skip the reading of timestamp as`firstMessage`appear to be null where it is supposed to be a valid message

**Comment by lancechant** [comment]
Awesome thanks @titou10titou10
