### ISSUE TITLE
REST: 415 Unsupported Media Type

### ISSUE THREAD

**Issue by jarojetu** [jmstoolbox/jmstoolbox#164]
## Specifications
- JMSToolBox version: v6.4.0
- OS (Name, version, 32/64bits): Win 10 64bit
- Q provider (kind, version) : IBM

Hi, Im trying to push the message through REST connector but getting the http 415 (Unsupported Media Type) code back. When the same message is inserted vi JMSToolbox as payload it is ok. Anyone has any idea what I'm doing wrong?

This is my request (anonymized - it is valid XML message):

`curl --location 'http://localhost:9998/rest/message/XX/XYZ' \
--header 'Content-Type: text/plain' \
--data '...message body removed...'`

Regards Jan

**Comment by titou10titou10** [comment]
JMSToolBox expect messages to be in JSON, not XML as explained in the WiKi section dedicated to the REST feature:

https://github.com/jmstoolbox/jmstoolbox/wiki/1.8-REST-Services#rest-listener

**Comment by titou10titou10** [comment]
"payloadText": "{"test": "Hello"}"

The type of the `payloadText`is string so you should escape the quotes:

    "payloadText": "{\"test\": \"Hello\"}"

This is valid JSON

**Comment by jarojetu** [comment]
Thanks again, yes this did the trick and it is working as expected!
