### ISSUE TITLE
Unable to connect to Azure Service Bus, client is freezing resulting in forced quit

### ISSUE THREAD

**Issue by jxc517** [jmstoolbox/jmstoolbox#166]
## Specifications
- JMSToolBox version:
- OS (Name, version, 32/64bits):
- Q provider (kind, version) :

## Expected Behavior
- Connect to Azure Service Bus without any manual jar loads [PS: Trying on Mac M1]

## Actual Behavior
- need to manually import close to six of netty dependencies
- Spinning forever and client freezes resulting in manual force quit and reopen to connect to other brokers

## Steps to Reproduce the Problem

  1. Download zip, run xattr to make it work on Mac
  2. Install bunch of dependencies, see screenshot
  3. Configure using ASB (premium tier) connection string or manual entry of host/port/user/password
  4. Try to connect to above configured ASB

## Logs
Eventually, attach the log files which are `"<user>\.jtb\JMSToolBox\jmstoolbox.log"` and `"<user>\.jtb\.metadata\.log"`    
They can be exported directly from JMStoolBox: Menu "Help" > "Export JMSToolBox log files..."

<img width="340" alt="image" src="https://github.com/jmstoolbox/jmstoolbox/assets/78751982/bd9ab333-e51f-42ec-bf22-4362458fa3d1">
[jmstoolbox.log](https://github.com/jmstoolbox/jmstoolbox/files/15091995/jmstoolbox.log)
[JTB_20242924_0504739_jmstoolbox.log](https://github.com/jmstoolbox/jmstoolbox/files/15091996/JTB_20242924_0504739_jmstoolbox.log)

**Comment by titou10titou10** [comment]
Not sure to understand. You setup a session as described [in the wiki here](https://github.com/jmstoolbox/jmstoolbox/wiki/2.14-Setup-for-Azure-SB) and JTB is unable to connect with lots of " Connection attempt" messages in the logs. right?

Then you added some jar dependencies and the result is the same?  or you managed to connect?

What version of Azuse SB are you using?

**Comment by jxc517** [comment]
Thanks for your prompt response and below are the details.

Not sure to understand. You setup a session as described [in the wiki here](https://github.com/jmstoolbox/jmstoolbox/wiki/2.14-Setup-for-Azure-SB) and JTB is unable to connect with lots of " Connection attempt" messages in the logs. right? **That is correct**

Then you added some jar dependencies and the result is the same? or you managed to connect? **I ended up adding extra jars as without them I got bunch of io.netty errors during connection. No I was not able to manage the client to connect to my ASB**

What version of Azuse SB are you using? **The only details I see on my ASB properties are these**
![image](https://github.com/jmstoolbox/jmstoolbox/assets/78751982/0d0375b1-b704-4c92-a680-d5ae125bf795)

**Comment by titou10titou10** [comment]
I do not see the logs where the connection failed after you added the extra jars
anyway, there are almost no chances it will work by adding jars that will conflict with the ones already embedded in JTB
I'v seen that tere are may jars that have newer versions, I will upgrade the jars in JTB

**Comment by titou10titou10** [comment]
I thing I  know what's going on...`netty-all jar`bundled with jtb does not include any netty classes

Could you make a new test by keeping only the netty-* jars as extra jar, except for netty-reactive-streams which is already bundled with JTB?

**Comment by jxc517** [comment]
As requested I only included below libraries but still the same issue

<img width="673" alt="image" src="https://github.com/jmstoolbox/jmstoolbox/assets/78751982/17b151da-0453-47b2-ba40-6ccc3b87d49d">
[jmstoolbox.log](https://github.com/jmstoolbox/jmstoolbox/files/15102358/jmstoolbox.log)

**Comment by titou10titou10** [comment]
Is there some messa«ge in`"<user>\.jtb\.metadata\.log"`? like ClassNotFound exceptions?

**Comment by jxc517** [comment]
I see a bunch of these, please see the attached log.
[abc.log](https://github.com/jmstoolbox/jmstoolbox/files/15123318/abc.log)

```
!ENTRY org.eclipse.e4.ui.workbench 4 0 2024-04-23 20:56:59.047
!MESSAGE Connect unsuccessful
!STACK 0
java.lang.ClassNotFoundException: io.netty.handler.codec.http.HttpMessage cannot be found by org.titou10.jtb.qm.azuresb_6.5.0.v20240327-1449
```

**Comment by titou10titou10** [comment]
Could you download the latest build version and test it?
Thanks

https://github.com/jmstoolbox/jmstoolbox/actions/runs/8869067450#artifacts

**Comment by jxc517** [comment]
That seems to be working and connected to ASB. Thanks a lot for your help.
