### ISSUE TITLE
Feature Request: Allow Carriage Return as line breaks in payload view

### ISSUE THREAD

**Issue by pmias** [jmstoolbox/jmstoolbox#171]
## Specifications
- JMSToolBox version: all
- OS (Name, version, 32/64bits): all
- Q provider (kind, version) : all

## Expected Behavior
Allow Carriage Return characters (0x0d) to act as line break in raw payload view, too.

## Actual Behavior
Only New Line characters (0x0a) are used as line breaks.

## Steps to Reproduce the Problem
Just view a message, which uses CR as line break.
E. g. the medical protocol format HL7 using CR to end a segment, which is effectively a line. The *lines* will be shown concatted in one single line.

## Logs
N/A

## Remark
I cloned the project and modified the class `org.titou10.jtb.ui.part.JTBMessageViewPart` in the dev branch by myself, by using a Pattern/Matcher object to unify all line breaks. Additionally I changed the font of the view to a Monospaced font, which really helps investigating these messages - allthough the font should be better configurable in the application settings.

**Comment by titou10titou10** [comment]
ok. could you propose a PR?
Thanks

**Comment by titou10titou10** [comment]
I merged the code in the dev branch
Changes from your code:
- Usage of SWTResourceManager as font resources must be properly disposed
- The possibility to display text message in monospaced font is controlled by a new preference field (false by default)
