### ISSUE TITLE
Enable Homebrew releases for project

### ISSUE THREAD

**Issue by pascalre** [jmstoolbox/jmstoolbox#177]
### Description
Currently, releases of this project are not available through Homebrew, which limits the ease of installation and updates for the users. This issue aims to address this limitation by enabling Homebrew releases for this project.

### Proposed Solution
To make this project available through Homebrew, a Homebrew formula has to be created that can be added to the official Homebrew repository. This formula will define the installation process and dependencies required for this project.

### Expected Benefits
Enabling Homebrew releases for this project will provide the following benefits to the users:

- Simplified installation process: Users can install this project with a single command, reducing the barrier to entry.
- Easy updates: Homebrew will handle updates, ensuring users have the latest stable version of this project.
- Consistent experience: Users familiar with Homebrew will have a familiar interface for managing this project.

**Comment by titou10titou10** [comment]
Good idea.
I have no idea on how Homebrew works and I do not have a Mac to test it, so....PR are welcome
Thanks

**Comment by pascalre** [comment]
@titou10titou10 I added a [PR](https://github.com/Homebrew/homebrew-cask/pull/180082) for this in homebrew. It got declined, because it is not signed (find details in the linked PR). Is there a way for you to sign upcoming releases?

**Comment by titou10titou10** [comment]
Currently no.

This question has been discussed many time before. Some examples:
 - #48 
 - #173 

Signing certificates are not free, and up to now, the advantages of buying/managing such certificate to ease the installation process is not obvious IMHO

**Comment by pascalre** [comment]
I created a custom brew tap for this in https://github.com/pascalre/homebrew-jmstoolbox
JMSToolBox can now be installed using `brew install --cask pascalre/jmstoolbox/jmstoolbox`

**Comment by titou10titou10** [comment]
Being a total newbee with brew, does this mean that anyone can install JTB with what you did, or is it kind of private? 
is there still need for some "code signature" or so?
Thx

**Comment by pascalre** [comment]
Anybody can install JMSToolBox with the above command using my public repo. No need for a signature. Since it is not part of the official homebrew tap, users can not find it in brew. You may want to document it anywhere, so that users are aware of this custom tap.

Updates are done with `brew upgrade jmstoolbox`.
