### ISSUE TITLE
JSON viewer does not work for a JSON Array

### ISSUE THREAD

**Issue by ccrowe-trimble** [jmstoolbox/jmstoolbox#182]
## Specifications
- JMSToolBox version: 6.6
- OS (Name, version, 32/64bits): 64 bit
- Q provider (kind, version) :

## Expected Behavior
Format JSON

## Actual Behavior
(No JSON text to show. The payload was probably not valid JSON)

## Steps to Reproduce the Problem

  1.Any json payload that starts with an array [] 
  
  
## Logs
2024-09-18 12:24:05:288 WARN  [o.t.j.u.FormatUtils         ] Problem occurred when parsing json : Cannot read JSON object, found JSON array

A JSON array valid as per RFC 8259 and https://jsonformatter.curiousconcept.com/

[ { "name" : "chris"}]

**Comment by titou10titou10** [comment]
Thanks for reporting. Problem fixed in beta and next version
GH build is here: https://github.com/jmstoolbox/jmstoolbox/actions/runs/10931697559
