### ISSUE TITLE
Show exception queue for OracleQA

### ISSUE THREAD

**Issue by remcocats** [jmstoolbox/jmstoolbox#184]
## Specifications
- JMSToolBox version:  v6.7.0
- OS (Name, version, 32/64bits): 
- Q provider (kind, version) : 

## Expected Behavior
When I connect to a OracleAQ JMS then I expect to see all the queues including the exception queues.

### What is a OracleAQ exception queue
The exception queue is the queue where the messages are going when they can't be consumed by the consumer.
With OracleAQ you can set a maximum retry. After the retry has been reached the message is sent back to the exception queue.
This is a specific OracleAQ exception queue. Other JMS providers have different solutions for message exceptions.

## Actual Behavior
When I connect to a OracleAQ JMS than I only see the created queues not the exception queues.

**Comment by titou10titou10** [comment]
OK. So with OracleAD, you want to see the Queues of type "EXCEPTION_QUEUE", right?
They should  show if you set the "Show system destinations.." in the preference. Did you tried it?

**Comment by remcocats** [comment]
I didn’t, I have written this pull request because a collage of mine had problems seeing the exception queue and was manipulating the jar for that. I think he didn’t saw that option or it wasn’t that clear. I wil tell him that he can set this option

**Comment by titou10titou10** [comment]
let me know if it works

**Comment by remcocats** [comment]
Hi it works thanks for the feedback

**Comment by titou10titou10** [comment]
Thanks . The question is this one: SHould JMSToolBox consider EXCEPTION_QUEUE type of queue as "system" or "temp" queues?
As i'm not an OracleQA user, I have no idea if the current implementation is right

**Comment by remcocats** [comment]
I think that its not a system or a temp queue. It is the counter partner of a normal queue. So every queue that is there has a exception queue where the messages are stored when it can’t be consumed

**Comment by titou10titou10** [comment]
OK. I will not consider them as system/temp queues
