### ISSUE TITLE
TIBCO EMS in not in the list of Queue Manager of Add Session -> connection

### ISSUE THREAD

**Issue by archills** [jmstoolbox/jmstoolbox#2]
## Specifications
- JMSToolBox version: V4.8.0
- OS (Name, version, 32/64bits): windows 7 pro 64 bit
- Q provider (kind, version) : tibco ems 8.3

## Expected Behavior

want to add a session of TIBCO EMS

## Actual Behavior

Cannot find TIBCO EMS in the dropdown list of queue manager.

## Steps to Reproduce the Problem

  1. click file -> new session
  2. click dropdown arrow of Queue Manager
     cannot find the TIBOCO EMS in the list.

BTW: I am a noob of JMS.  
![image](https://user-images.githubusercontent.com/33689955/37317806-0a2b2b38-26bb-11e8-8af9-0bf1172c19b6.png)

**Comment by titou10titou10** [comment]
Did you configured JMSToolBox with the proprietary jar required for TIBCO?
The procedure is specified [here](https://github.com/jmstoolbox/jmstoolbox#configuring-a-queue-provider)  and the required jars and how to setup a TIBCO session are detailed [here](https://github.com/jmstoolbox/jmstoolbox/wiki/2.12-Setup-for-TIBCO-ems)

**Comment by archills** [comment]
Thanks. I haven't got the jar from EMS yet. So for TIBCO EMS, after jar files is added in tab"Q managers", then TIBCO EMS would appear in the dropdown list?

**Comment by titou10titou10** [comment]
Yes, it should be there...

**Comment by titou10titou10** [comment]
Hi. Is your problem solved?

**Comment by titou10titou10** [comment]
Closing as no feedback received recently. Please reopen this bug if it still a problem
