### ISSUE TITLE
Feature request: Change type of JMS properties

### ISSUE THREAD

**Issue by elendis** [jmstoolbox/jmstoolbox#21]
## Specifications
- JMSToolBox version: latest

## Expected Behavior
When sending a message, we would like to be able to change the type of JMS properties (e.g. set a property to type "double").

## Actual Behavior
All JMS properties are strings.

**Comment by titou10titou10** [comment]
Thanks for using JMSToolBox

Could you describe your exact use case?

With JMS`"javax.jms.Messages"`, all type of supported properties can be get/set by calling the`getStringProperty()`/`setStringProperty()`method on the message, in addition to the more specific getters/setters methods (ie `getDoubleProperty()`

On a technical point of view, JMSToolBox does not consider "*All JMS properties are strings*", as they can  be get/set as string from the specs

More [information in the JavaDoc](https://docs.oracle.com/javaee/7/api/javax/jms/Message.html)

So if you post a message with JMSToolBox with a property with a value that can be converted to a `double` (ie `12.34`) , you can consume the JMS message in a java program by using either `getDoubleProperty()`or `getStringProperty()`

Denis

**Comment by elendis** [comment]
Hi Denis,

I checked and you are right of course - the automatic conversion works just fine when using the getters. In our usecase, however, we want to use the properties in a message selector. The Javadoc states:

> The conversions that apply to the get methods for properties do not apply when a property is used in a message selector expression.  For example, suppose you set a property as a string value, as in the following:
> 
> myMessage.setStringProperty("NumberOfOrders", "2");
> 
> The following expression in a message selector would evaluate to false, because a string cannot be used in an arithmetic expression:
> 
> "NumberOfOrders > 1"

Our usecase is pretty similar to this example - we want to set a message version property as a double and use it to select our messages, e.g. every message with a version > 2.0. So unfortunately, the automatic conversion doesn't help us here. 

elendis

**Comment by titou10titou10** [comment]
OK...
Sorry I'm little lost here.
What blocks you from writing`"version > 2.0"`in the selector selection box?
Maybe what you would like, is, in addition to the`"Use as selector"`or `"Build selector"`contextual menus on headers/properties, a new `"Use as non-string selector"`(or similar) menu that will generate the selector without the quotes. Is that correct?
Denis

**Comment by elendis** [comment]
Hi Denis,

we use JMS Toolbox to send messages, but the consumers (with the message selector) are Apache Camel routes. When creating messages with JMSToolbox (mainly to test certain scenarios), we can add a property "MessageVersion" with a value "2.0", but our Apache Camel routes won't pick them up when using a message selector like this:

> JMSType = 'TestMessage' AND MessageVersion = 2.0

The selector itself isn't the problem - we wrote a small script to send test messages, and they are getting picked up by the routes without problem. The script sets the MessageVersion property as type double.

I should have been clearer on our use case, sorry.

elendis

**Comment by titou10titou10** [comment]
Understood.
And you are right, this is a problem in JMSToolBox. 
Even if there is no metadata fo querying the class of a property, the JMS engine stores it somewhere.     
A call to `"Message.getObjectProperty(....)"`method returns the property as an `"Object"` and calling `"getClass()"`on that object return the real class (`"Double"`, `"String"` etc)
In the panel to add properties to a message, I will a drop-down list to choose the type of the property, and JTB will issue the right call to set the property in the message with the right type
Thanks for reporting
Denis
