### ISSUE TITLE
Topic subscription does not work properly, only one message is displayed in all cases

### ISSUE THREAD

**Issue by ruffp** [jmstoolbox/jmstoolbox#27]
## Specifications
- JMSToolBox version: V4.12.1 
- OS (Name, version, 32/64bits): Linux CentOS 6.9 64bits
- Q provider (kind, version): ActiveMQ 5.10.2 / OpenWire connection (61616)

## Expected Behavior
When subscribing to a topic, more than one messages should be displayed if the Maximum message is set to more than 1.

When the settings is 0 it should display /catch all messages of the topic.

## Actual Behavior
Despite the setting "Maximum message displayed" is configured to 50, only one message is displayed.
Changing the setting to (0 to 200) does have the same effect.

If there is a continuous flow of messages, stopping the subscription and starting again will catch another message instance (but only 1).

### Note
I cross-checked with another tool for subscribing the same Topic and I can catch all the messages (to be sure they were not lost).

## Steps to Reproduce the Problem

  1. Setup OpenWire connection: failover://(tcp://host-1.mydomain.net:61616,tcp://host-2.mydomain.net:61616)
  2. Setup JMX connection: 
	    1: host-1.mydomain.net:1099
	    2: host-2.mydomain.net:1099
  3. Scenario-1 - Subscribe to a Topic, "Max Messages Displayed" = 50 (default value)
  4. Few messages sent to Topic (between ~5)
  5. Only first messages is catched in the UI (and in the logs)
  6. Scenario 2 - Change "Max Messages Displayed" = 200 
  7. Stop subscribing to the Topic
  8. Subscribe to the Topic
  9. Few messages sent to Topic (between ~5)
  10. Only first messages is catched in the UI  (and in the logs)

## Logs
Eventually, attach the log files which are `"<user>\.jtb\JMSToolBox\jmstoolbox.log"` and `"<user>\.jtb\.metadata\.log"`    
They can be exported directly from JMStoolBox: Menu "Help" > "Export JMSToolBox log files..."

Same log as in initial ticket. Not more useful information in versions 4.11.0 or 4.12.1.

jmstoolbox.log:

2018-07-19 11:49:40:655 DEBUG [.c.JTBSessionContentViewPart] Starting subscription
2018-07-19 11:49:40:681 DEBUG [.c.JTBSessionContentViewPart] Subscription started.
2018-07-19 11:49:46:451 DEBUG [o.t.j.u.p.c.TopicListener   ] JTBTopic [MY_TOPIC.Mirrored] : Received message with id 'ID:HOST-2-49314-1531796445858-139:1:2:1:1484'
2018-07-19 11:50:09:031 DEBUG [.c.JTBSessionContentViewPart] Stopping subscription
2018-07-19 11:50:09:031 DEBUG [.c.JTBSessionContentViewPart] Subscription stopped.
2018-07-19 11:50:10:096 DEBUG [.c.JTBSessionContentViewPart] Starting subscription
2018-07-19 11:50:10:115 DEBUG [.c.JTBSessionContentViewPart] Subscription started.
2018-07-19 11:50:16:540 DEBUG [o.t.j.u.p.c.TopicListener   ] JTBTopic [MY_TOPIC.Mirrored] : Received message with id 'ID:HOST-1-49310-1531814581012-127:1:2:1:1524'
2018-07-19 11:50:53:042 DEBUG [.c.JTBSessionContentViewPart] Stopping subscription
2018-07-19 11:50:53:043 DEBUG [.c.JTBSessionContentViewPart] Subscription stopped.
2018-07-19 11:50:56:375 DEBUG [.c.JTBSessionContentViewPart] Starting subscription
2018-07-19 11:50:56:391 DEBUG [.c.JTBSessionContentViewPart] Subscription started.
2018-07-19 11:51:07:711 DEBUG [o.t.j.u.p.c.TopicListener   ] JTBTopic [MY_TOPIC.Mirrored] : Received message with id 'ID:HOST-2-49314-1531796445858-139:1:2:1:1489'
2018-07-19 11:51:21:307 DEBUG [o.t.j.u.p.JTBMessageViewPart] JTBMessageViewPart refresh for JTBMessage [jtbDestination=MY_TOPIC.Mirrored, jmsMessage ID=ID:HOST-1-49310-1531814581012-127:1:2:1:1524, jtbMessageType=TEXT, replyToDestinationName=MY_TOPIC_RESPONSE, deliveryMode=PERSISTENT, priority=4, timeToLive=null, deliveryDelay=null]
2018-07-19 11:51:21:376 DEBUG [o.t.j.h.MessageViewHandler  ] execute. Message = [JTBMessage [jtbDestination=MY_TOPIC.Mirrored, jmsMessage ID=ID:HOST-1-49310-1531814581012-127:1:2:1:1524, jtbMessageType=TEXT, replyToDestinationName=MY_TOPIC_RESPONSE, deliveryMode=PERSISTENT, priority=4, timeToLive=null, deliveryDelay=null]]

**Comment by titou10titou10** [comment]
I tested it on my test system and it works:

1. start JMSToolBox
2. in the preference , set the`"Limit message captured per topic"` to 50
3. connect to a session for ActiveMQ (v5.15.5 in my case)
4. double click on a topic to start the capture (the`"Maximum number of messages captured and displayed"`is 50)
5. use the ActiveMQ web console to post a message to the topic
    -> the message appears in JTB
6. use the ActiveMQ web console to post a second mesage to the topic
    -> the second message appears in JTB
    -> there is 2 messages displayed 
7. use JMSToolBox to post a third mesage to the topic
    -> the third message appears in JTB
    -> there is 3 messages displayed in the message viewer

In your case, do you have messages appearing in the server logs?
I'll try to find the time to install a v5.10.2 server

**Comment by ruffp** [comment]
I repeated your scenario and posted directly in a TEST topic from another client and it still get only one message. 
I also tested with my local instance of AMQ (localhost) and I still have the same issue (then not related to master/slave setup). 
In the log it is like I get only one as well and no errors (see attached file). 
I just start subscribing, sent 10 messages in the topic from ActiveMQBrowser, got only one, open it, and  open "Destination Information" of topic TEST_JTB.

Did you also test under Linux? 

Another point, I did not changed my connection since I  was in a previous version (4.9.x) should I change some properties in the connectivity with ActiveMQ?

**Comment by titou10titou10** [comment]
Just done the previous scenario on my Ubuntu 17.04 test workstation with JTB v4.12.1. ActiveMQ v5.14.5 is also running in the same workstation and it works as you can see on the following printscreen (With max message capture set to 3)

- I cant find the attached file you are talking about in your post
- No you don't have to change anything in your session definition
- Q: Why do you mention "Destination informatioN" in your post? is there a relation to the problem?
- In the message brower, you see one message. Q: is it the last one you just post? or is it always the same message?
- WIth ActiveMQ it is possible on the server to limit the number of message the server keeps per consumer with the`"constantPendingMessageLimitStrategy" `property . Maybe you are in this case? http://activemq.apache.org/slow-consumer-handling.html
Denis



![screenshot from 2018-09-27 20-15-13](https://user-images.githubusercontent.com/15241034/46181158-249bbc80-c292-11e8-9516-0c6acf20685e.png)

**Comment by titou10titou10** [comment]
(sorry close the issue by mistake)

**Comment by ruffp** [comment]
Sorry for the file, the upload did not work from my linux centos (too old chromium).

I retried it and still the same: 

I tried to change disk permission (root:users to the folder /opt/JMSToolbox).

The log and the GUI only gets' the first message.

See the screenshot, I used ActiveMQBrowser to send to the queue and listen to the .mirrored topic; if there will be a problem in my config, the other client would also be impacted I think.

![capture-jtb](https://user-images.githubusercontent.com/2510180/46406447-dd874e80-c70b-11e8-9c0b-fedd9ca687f6.png)

**Comment by titou10titou10** [comment]
Weird...
You can mail me the 2 logs files directly to [titou10.titou10@gmail.com](mailto:titou10.titou10@gmail.com)
Thanks

**Comment by ruffp** [comment]
I attached the jtb log in the comment (26 days old). The other log did not catch anything.

I have to mention that one of my colleague have also the same issue (from his Windows 10 machine).
I also suspect a setting on broker side that makes that effect, however that would not explain why the ActiveMQBrowser client is working with the same broker.

Our activeMQ is configured like this:

`<broker xmlns="http://activemq.apache.org/schema/core" brokerName="localhost" dataDirectory="${activemq.data}" useJmx="true" useTempMirroredQueues="false" schedulerSupport="false">
	<destinationInterceptors>
		<mirroredQueue copyMessage="true" postfix=".Mirrored" prefix=""/>
	</destinationInterceptors>
...`

where ${activemq.data} points to a network shared drive.

**Comment by titou10titou10** [comment]
Maybe, it is something related to message acknowledgment of your server. 
In JTB, in the Topic listener`"onMessage()"`method, I do not perform a `"commit"`.  The session is created as`"Transacted"`in JTB.
You can see that in the logs where there is a `"begin:TX"` without any following `"Commit: TX"`
It does not cause any problem in my 3 ActiveMQ test servers but maybe yours is configured differently in that matter 
I will change the code to perform a`"commit"`after JTB captured the message for safety
I'm not sure if it will solve the problem here

**Comment by titou10titou10** [comment]
(Closed by error..again..)

**Comment by ruffp** [comment]
Interesting, I think I the origin of the problem:

In our activemq.xml we have the specific topic policy: 

`<policyEntry topic=">" producerFlowControl="false" topicPrefetch="1">
 <pendingMessageLimitStrategy>
   <constantPendingMessageLimitStrategy limit="1000"/>
 </pendingMessageLimitStrategy>
</policyEntry>`

and if I change the topicPrefetch to 5, I would get the 5 first messages until I stop and restart the listening session.

In [that article](https://activemq.apache.org/what-is-the-prefetch-limit-for.html) they state: 

> Once the broker has dispatched a prefetch limit number of messages to a consumer it will not dispatch any more messages to that consumer until the consumer has acknowledged at least 50% of the prefetched messages, e.g., prefetch/2, that it received. When the broker has received said acknowledgements it will dispatch a further prefetch/2 number of messages to the consumer to 'top-up', as it were, its prefetch buffer. Note that it's possible to specify a prefetch limit on a per consumer basis (see below).

and then, I think it would be better to send an acknowledge (commit) every time you read an event.

Note that the other client should already do that as I receive all the messages with the same setting.

**Comment by titou10titou10** [comment]
Cool. 
Yes, this is what I [commited yesterday](https://github.com/jmstoolbox/jmstoolbox/commit/27073117304f901247baf00b84aa5e6a392e3976), ie commit in the Message Listener on message captured
It will be in v4.13.0

**Comment by ruffp** [comment]
hi, I confirm the bug is fixed with the 4.13.0.
Many thanks!

**Comment by titou10titou10** [comment]
Great!

**Comment by titou10titou10** [comment]
Hi,
If you can, could you verify that JMSToolBox v4.14.0 still works with your ActiveMQ setup?
I had to change something related to this bug in as it was breaking IBM MQ plugin. JMS specs say that it is not allowed to perform a commit in such situation and IBM MQ strictly enforce this. I  replaced the "transacted JM Session" used to capture topics with a session with "auto-acknoledge" activated.
On my test workstation with similar setup as yours it works, but I want to be sure it still works with your setup
Thanks
Denis
