### ISSUE TITLE
Cannot create a ActiveMQ session

### ISSUE THREAD

**Issue by glockenstein** [jmstoolbox/jmstoolbox#28]
## Specifications
- JMSToolBox version: 4.12.1
- OS (Name, version, 32/64bits): Neon Linux, Ubuntu 16.04 LTS based, 64 bit
- Q provider (kind, version) : ActiveMQ

## Expected Behavior
able to create a session

## Actual Behavior
cannot create a session, get the message property 'trustAllPackages' must be of kind 'BOOLEAN'

## Steps to Reproduce the Problem

  1. call File / New Session
  1. enter the required details at the connection page
  1. press create button

## Logs
no information regarding this problem in the logs, definition of a system property does not change this behaviour

**Comment by glockenstein** [comment]
It seems that the properties tab has a problem in my setup. I thought it was a read only table and the properties have to be defined as system properties. 
If I click at a cell or row sometimes an input field appears below the table and sometimes nothing happens and i have to type without seeing anything but after pressing enter the text ist added somewhere in the value.
Is it possible that your program does not work with OpenJDK?

**Comment by glockenstein** [comment]
Yes. This helps. Thank you.

**Comment by titou10titou10** [comment]
For reference, the bug in Ubuntu/GTK:
https://bugs.launchpad.net/ubuntu/+source/java-common/+bug/1552764

**Comment by titou10titou10** [comment]
Relates to #30
