### ISSUE TITLE
NPE while running scripts against templates.

### ISSUE THREAD

**Issue by ssrini10g** [jmstoolbox/jmstoolbox#32]
## Specifications
- JMSToolBox version: V4.12.1 (2018-09-12 15:43)
- OS (Name, version, 32/64bits):  Windows, 64
- Q provider (kind, version) :  IBM MQ
## Expected Behavior
   to post to the destination queue
## Actual Behavior
NPE

## Steps to Reproduce the Problem

  1. script a template to a destination queue
   issue is very similar to https://github.com/jmstoolbox/jmstoolbox/issues/26 
   but am already using V4.12.1

## Logs
[JTB_20182517_2010217_eclipse.log](https://github.com/jmstoolbox/jmstoolbox/files/2489065/JTB_20182517_2010217_eclipse.log)
[JTB_20182517_2010217_jmstoolbox.log](https://github.com/jmstoolbox/jmstoolbox/files/2489066/JTB_20182517_2010217_jmstoolbox.log)

**Comment by titou10titou10** [comment]
As a workaround if you can not wait for v4.13.0, you can edit the templates used in the script and add any property with any value.. It should work
