### ISSUE TITLE
The application “JMSToolBox.app” can’t be opened.

### ISSUE THREAD

**Issue by heka-pulsen** [jmstoolbox/jmstoolbox#33]
## Specifications
- JMSToolBox version: 4.13.0 (same issue in previous versions)
- OS (Name, version, 32/64bits): MacOS Mojave 10.14
- Q provider (kind, version) :

## Expected Behavior
When starting JMSToolbox from the Launchpad it should start

## Actual Behavior
When starting JMSToolbox it fails with this message:
The application “JMSToolBox.app” can’t be opened.

## Steps to Reproduce the Problem

  1. Download JMSToolbox from github
  2. Extract JMSToolbox.app from the downloaded archive and drop it into Applications
  3. Start it from the Launchpad

## Workaround
Start a terminal and do this:
cd /Applications/JMSToolBox.app/Contents/MacOS
chmod +x JMSToolBox

**Comment by titou10titou10** [comment]
Hi,
This is not exactly a "bug"
The workaround you provide is actually the "official procedure to run JMSToolBox on Mac OS as explained [here](https://github.com/jmstoolbox/jmstoolbox)
This is a current limitation of eclipse that JMSToolBox is based on
I'll track if that changed in the lates version of eclipse
Denis

**Comment by heka-pulsen** [comment]
I'm using multiple Eclipse based tools on MacOS and this is the only one I need to manually set execute permissions on, so there must be a way to do this...
/Henrik

**Comment by titou10titou10** [comment]
To be more precise, this is a bug when you package the applicationfrom a Windows machine with eclipse tycho
So yes, if you build/package from a Mac machine the execution flag is set.
Unfortunately I don't have access to a Mac myself, so setting manually the execution flag manually is currently the way to go
FMI, could you give me the name of other open source eclipse RCP based tools you are using on your Mac? I will check how they build / package their applications and, if they build from Windows, see how they manage the execution flag
Thanks

**Comment by heka-pulsen** [comment]
The only other open source eclipse based tool I'm using is Apache Directory Studio. 
Would it work if you build the project from a Linux VM?

**Comment by patrickneubauer** [comment]
Hello,

after following the instructions stating to add execution privileges to JMSToolBox and selecting "Open Anyway" in the macOS system security settings, I am unable to successfully launch the application.

![error-popup](https://i.imgur.com/DVsMOEF.png)

This occurred on macOS Mojave 10.14.3, Java 1.8.0_141.

Cheers, Patrick

**Comment by titou10titou10** [comment]
JMSToolBox v5.x+ requires Java  11 (And GTK 3+,,,) as [stated here](https://github.com/jmstoolbox/jmstoolbox/releases/tag/v5.0.0)

**Comment by andreacomo** [comment]
Hi,
on Catalina (10.15.3), I also had to:
 
* execute `xattr -cr /path/to/JMSToolBox.app` from terminal, otherwise application was considered "corrupted".
* set jdk 11 as described in [Eclipse documentation](https://wiki.eclipse.org/Eclipse.ini#-vm_value:_Mac_OS_X_Example), because I cannot replace default system jdk (1.8), in `/path/to/JMSToolBox.app/Contentes/Eclipse/JMSToolBox.ini`.

just my two cents.

Cheers

**Comment by titou10titou10** [comment]
Thx @andreacomo , I've updated the READE.ME file

**Comment by sukanth** [comment]
i am not able to open JMSToolBox on M1 Macbook pro any thoughts ? i am using java 11 and have changed the JMSToolBox.ini file to update the vm and vmargs to point java to <code>/Users/<YOUR_USER>/.sdkman/candidates/java/11.0.8.hs-adpt/lib/jli/libjli.dylib</code>@titou10titou10 
<img width="1724" alt="image" src="https://user-images.githubusercontent.com/8810504/161395413-bf13317e-0377-475e-a38c-d6ca9759f56d.png">

**Comment by CoreForce** [comment]
Still an issue with 5.13 for both Intel and AppleSilicon machines.
I think it's a bug, an application freshly installed should work out of the box.
If the framework used does not support this, please reconsider framework or installer used.

**Comment by sukanth** [comment]
Its not working out of the box for me but , i have got this working by tweaking 

1. JMSToolBox.ini file
`-vmargs
-Dosgi.requiredJavaVersion=11`
`-vm
/Users/<UserName>/.sdkman/candidates/java/jdk-11.0.13.jdk/lib/jli/libjli.dylib`
2.  Change permissions on JMSToolBox executable file
`chmod 777 JMSToolBox`
3.  Add this to info.plist
` <string>-vm</string><string>/Library/Java/JavaVirtualMachines/jdk-11.0.13.jdk/Contents/Home/bin/java<string>`
4. change directory to the application root and execute below command
`xattr -cr JMSToolBox.app`

**Comment by adelinor** [comment]
Cheers @andreacomo and @sukanth ! You saved my day :disappointed_relieved:
