### ISSUE TITLE
IBM MQ No longer appears in session list

### ISSUE THREAD

**Issue by davsucks** [jmstoolbox/jmstoolbox#41]
## Specifications
- JMSToolBox version: 5.0.0
- OS (Name, version, 32/64bits): MacOs High Sierra 10.13.6

## Expected Behavior
I should be able to create new sessions with IBM MQ

## Actual Behavior
I'm no longer seeing IBM MQ as an option when creating a new session.

<img width="254" alt="screen shot 2019-02-08 at 2 08 27 pm" src="https://user-images.githubusercontent.com/6392881/52500556-485e0000-2bac-11e9-99fb-bc9a0ea6fc6f.png">

## Steps to Reproduce the Problem

  1. Click Create New Session
  2. Click Queue Manager dropdown
  3. See IBM MQ is no longer there.

**Comment by titou10titou10** [comment]
Could you send me  the 2 JMSToolBox logs files? (Start JMSToolBox, menu Help > Export JMSToolBox log files)     
My email: [titou10.titou10@gmail.com](mailto:titou10.titou10@gmail.com)
Thanks 
Denis

**Comment by titou10titou10** [comment]
After reviewing the logs, it appeared that the "IBM MQ" Q Manager was not configured to use the`"com.ibm.mq.allclient.jar"` jar required for IBM MQ as explained in the [Wiki here](https://github.com/jmstoolbox/jmstoolbox/wiki/2.1-Setup-for-IBM-MQ)

Adding the jar solved the problem
