### ISSUE TITLE
New feature to show message count behind queue

### ISSUE THREAD

**Issue by uzijazi** [jmstoolbox/jmstoolbox#45]
## Specifications
- JMSToolBox version: 5.0.0
- OS (Name, version, 32/64bits): Windows 10 (1809) x64
- Q provider (kind, version) : ActiveMQ (5.14.5)

## New feature
Make it possible to show some of the destination information behind a queue or topic, like 'EnqueueCount'.

**Comment by titou10titou10** [comment]
It's already there...
Connect to an ActiveMQ server thenright click on a Queue or Topic > "Destination Information"
Do you need something more than what is displayed in the "Destination Information"  panel?
Denis

**Comment by uzijazi** [comment]
That is totally correct, but as we have more than 20 queues and also more topics, it's not nice to right click all queues/topics. Maybe it would be nice to see a configured information after each queue/topic in the tree view.

**Comment by titou10titou10** [comment]
In the meantime, as a workaround, if your specific need is to see the depth of all the Queues in one place, as the title of your feature request suggests, you can use the "Queue Depth" browser.
For this, either

- double click on the "Queue" folder in the session tree browser, 
- right click on the session > "Show Queues depth" . From there you can enable enable the auto refresh of the browser and filter the queues you want to see there

Note that the queue depth is obtaines with the`"QueueSize"` JMX attribute and not the`"EnqueueCount"`, as`"EnqueueCount"` is not the current Queue depth..

**Comment by uzijazi** [comment]
Thank you! This was _one_ thing I was searching for. But maybe the other thing is quite interesting to you, too?

**Comment by titou10titou10** [comment]
Excellent
In fact not really, mostly because there is not much space there and it can hit performance . Reading the Q depth or other information on tenths of destinations shown in the tree browser may take time. And data there will not be refreshed
Putting other information there is also tricky as no Q Manager as the same set of metrics/JMX variables and it will not be refreshed too.
So I will not add anything there
Denis
