### ISSUE TITLE
destination queue in destination Info for alias en remote queues

### ISSUE THREAD

**Issue by EddeBijDUO** [jmstoolbox/jmstoolbox#50]
## Specifications
- JMSToolBox version: v4
- OS (Name, version, 32/64bits): Windows 64bits
- Q provider (kind, version) : IBM MQ v9

Enhancement request

## Expected Behavior
I would expect to see the destination queue in the destination info. When the queuetype is an alias or remote queue it points towards another destination. Could you please include that destination name in the destination info (details of a queue). Maybe the field ResolvedQName is the intended field for that. But it remains empty when I select a queue (either type alias or -remote)

And please make the destination info selectable (So I can copy the info to a text file)

## Steps to Reproduce the Problem

  1. Select a (alias or remote) queue
  1. context menu -> destination Information

**Comment by titou10titou10** [comment]
The`"ResolvedObjectString"`,`"ResolvedQName"`and`"ResolvedType"`attributes and all the other attributes comes directly from MQ
Namely from the [com.ibm.mq.MQQueue](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.1.0/com.ibm.mq.javadoc.doc/WMQJavaClasses/com/ibm/mq/MQQueue.html) class. The description for those 3 variables is in the [MQOPEN function](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.1.0/com.ibm.mq.mon.doc/q037750_.htm)
It appears that in your case those fields are empty, and so JMSToolBox show those fields as-is. There is currently no plan for JMSToolBox to display more info than MQ provides directly
Your last request is included in the other issue you opened
