### ISSUE TITLE
Connect unsuccessful 

### ISSUE THREAD

**Issue by uzijazi** [jmstoolbox/jmstoolbox#56]
## Specifications
- JMSToolBox version: 5.3.0
- OS (Name, version, 32/64bits): Windows 10 Pro x64 (1903)
- Q provider (kind, version) : ActiveMQ 5.14.5

## Expected Behavior
Double click should connect to Broker

## Actual Behavior
Exception is thrown

## Steps to Reproduce the Problem

  1. Unpack JMSToolBox 5.3.0 zip
  2. Open Application
  3. Double click on any Broker
  4. Exception is thrown : 

java.lang.ClassNotFoundException: javax.management.j2ee.statistics.Statistic cannot be found by org.titou10.jtb.qm.activemq_1.0.0.201906111154
javax.management.j2ee.statistics.Statistic cannot be found by org.titou10.jtb.qm.activemq_1.0.0.201906111154

## Logs
[jmstoolbox.log](https://github.com/jmstoolbox/jmstoolbox/files/3276607/jmstoolbox.-.Kopie.log)

**Comment by titou10titou10** [comment]
Yes, this is a bug
Please stay with v5.2.0 for now 
Sorry for that
