### ISSUE TITLE
Error connecting to a ActiveMQ Artemis 1.5.5 broker - AMQ222112

### ISSUE THREAD

**Issue by raddave** [jmstoolbox/jmstoolbox#6]
Bonjour Denis,

## Specifications
- JMSToolBox version: 4.8.0
- OS (Name, version, 32/64bits): 64-bits
- Q provider (kind, version) : Apache ActiveMQ Artemis 1.5.5 and using artemis-core-client-1.5.5.jar

## Expected Behavior
List destinations after successful connection

## Actual Behavior
Internal Error Popup
Log shows:
`2018-03-20 11:30:26:646 ERROR [o.t.j.u.JTBStatusReporter   ] Connect unsuccessful
java.lang.ClassCastException: java.lang.String cannot be cast to [Ljava.lang.Object;
	at org.titou10.jtb.qm.artemis.ActiveMQArtemisQManager.discoverDestinations(ActiveMQArtemisQManager.java:183) ~[na:na]
	at org.titou10.jtb.jms.model.JTBConnection.connect(JTBConnection.java:277) ~[na:na]
	at org.titou10.jtb.handler.SessionConnectHandler$1.run(SessionConnectHandler.java:111) ~[na:na]
....`

On the broker side, the following exception is logged:

`2018-03-20 15:26:42,308  WARN {Thread-1 (activemq-netty-threads)} [o.a.a.a.c.server:413] AMQ222112: exception while retrieving attribute queueNames on jms.server
				java.lang.IllegalStateException: Problem while retrieving attribute queueNames
	at org.apache.activemq.artemis.core.server.management.impl.ManagementServiceImpl.getAttribute(ManagementServiceImpl.java:688)
	at org.apache.activemq.artemis.core.server.management.impl.ManagementServiceImpl.handleMessage(ManagementServiceImpl.java:407)
...`

## Steps to Reproduce the Problem

  1.
  1.
  1.

**Comment by titou10titou10** [comment]
Hi,
Did you follow the steps for Artemix v1x as described in the wiki page [here](https://github.com/jmstoolbox/jmstoolbox/wiki/2.6-Setup-for-Apache-Artemis) ?    
What do you mean by *"using artemis-core-client-1.5.5.jar"* ? did you configured JTB with your own set of jars (you should not as JTB already embed artemis v1.5.x jars...)?
Could you reproduce the problem and attach here the 2 logs files of JTB  or send them to me:    [titou10.titou10@gmail.com](mailto:titou10.titou10@gmail.com). The logs are: `"<user>\.jtb\JMSToolBox\jmstoolbox.log"` and `"<user>\.jtb\.metadata\.log"`
Thanks

**Comment by raddave** [comment]
I did follow the steps on the Wiki page except for one thing:  I updated the Artemis Q Manager config with the latest artemis-core-client-1.5.5.jar .  I had a previous JTB installatation (don't know the version) for which I had probably setup a client jar.  I've just decided to delete the <user>\.jtb directory and start from scratch.  Same error though.  Logs sent via email.  thanks.

**Comment by titou10titou10** [comment]
From your logs It seems your server is in a live/backup topology and the problem may come from there:
[...]**received backup update for live/backup pair = TransportConfiguration [...] but it didn't belong to TransportConfiguration[...]**

````
Trying to connect with connectorFactory = org.apache.activemq.artemis.core.remoting.impl.netty.NettyConnectorFactory@78b7f805, connectorConfig=TransportConfiguration(name=6dbb0765-2c66-11e8-a634-005056c00008, factory=org-apache-activemq-artemis-core-remoting-impl-netty-NettyConnectorFactory) ?port=61621&host=xxxxxx
Started Netty Connector version 4.1.5.Final
Remote destination: xxx/xxx.xxx.xxx.xxx:61621
Reconnection successful
ClientSessionFactoryImpl received backup update for live/backup pair = TransportConfiguration(name=6dbb0765-2c66-11e8-a634-005056c00008, factory=org-apache-activemq-artemis-core-remoting-impl-netty-NettyConnectorFactory) ?port=61621&host=xxxxxx / null but it didn't belong to TransportConfiguration(name=6dbb0765-2c66-11e8-a634-005056c00008, factory=org-apache-activemq-artemis-core-remoting-impl-netty-NettyConnectorFactory) ?port=61621&host=xxxxxx 
connected to xxxxxx xxxxxx
discoverDestinations : org.apache.activemq.artemis.jms.client.ActiveMQConnection@7aea704c - false
Connect unsuccessful
java.lang.ClassCastException: java.lang.String cannot be cast to [Ljava.lang.Object;
	at org.titou10.jtb.qm.artemis.ActiveMQArtemisQManager.discoverDestinations(ActiveMQArtemisQManager.java:183) ~[na:na]
````

Q: do you have other JMS client to connect to this server and work fine?
I have no idea what is wrong here, probably a configuration problem on the server side, or maybe a missing property on the client?
If you google `"but it didn't belong to TransportConfiguration"`, you'll find many people with similar problem, many from HornetQ (which is one of the ancestor of Artemis with ActiveMQ..)
In the meantime I'll change the code for v4.9.0 in order to display that mysterious "String" received instead of an array of String with the name of the queues recevived by JMSToolBox

**Comment by raddave** [comment]
Answer Q1: yes we do.  They're local client but I've just configured a remote client as a unit test and it's able to send a message.

Answer Q2: server-side, same error as yours.  We do have a 1.5.5 broker.  Having a look at the JTB's ActiveMQArtemisQManager class, I noticed that you use the ResourceNames.JMS_SERVER resource name to retrieve queueNames, just as we do in our tests.  However, it seems this resource name isn't visible for a remote client (are you using an external broker or embedded for your tests?).  I tried to expose explicitly the core queue as a jms queue in the broker.xml file using :

  <jms xmlns="urn:activemq:jms">
  	<queue name="<queue_name>"/>
  </jms> 

ResourceNames.JMS_SERVER still not exposed.

When using ResourceNames.CORE_SERVER, our remote client is able to retrieve the queue names.  

I don't know if changing JTB's ActiveMQArtemisQManager resource name to CORE_SERVER might have an impact on backward compatibility but as you probably know, JMS_SERVER resource name as been removed in version 2.0.

**Comment by titou10titou10** [comment]
> However, it seems this resource name isn't visible for a remote client 

Q: what do you mean by`"remote client"`? ie JTB is installed on a different server that the Artemis server?

The exception you copied in your initial message says that `exception while retrieving attribute queueNames on jms.server`. This may indicate that  `jms.server` exists but without the `queueNames` attribute? I'll try to find time to dig in the Artemis source code

Q: Could it be a a security/authorisation problem wit the user you are using in JTB?

> are you using an external broker or embedded for your tests?)

My test server use a standalone server of Artemis v1.5.5 (And now v1.5.6), and JTB and JTB on win /64 accesses the server with "localhost". I will try to install JTB in a different place and acces it "remotely"

> JMS_SERVER resource name as been removed in version 2.0.

Yes this why there is a specific plugin for Aretmis v2.x. Many many other things have also changed between v1.x and 2.x, so the specific JTB plugin (And even between v2.0 and 2.1 they changed the API., check the JTB source for artemis 2.x..)

**Comment by titou10titou10** [comment]
About my remark on the conenctor/acceptor problem, from the [v1.5.5 doc](https://activemq.apache.org/artemis/docs/1.5.5/configuring-transports.html) section "Configuring Transport" :
>Don't forget to specify a host name or IP address! If you want your server able to accept connections from other nodes you must specify a hostname or IP address at which the acceptor will bind and listen for incoming connections. The default is localhost which of course is not accessible from remote nodes!

I'll test it tonight from a remote machine

**Comment by raddave** [comment]
Hello Denis,

Here we are.  Our broker is started using an instance of EmbeddedActiveMQ instead of the more specific EmbeddedJMS .  This explains your EDIT2 .

However, this leaves us wondering why we have JMS clients interacting successfully with the broker (including topic subscribers). There must be some magic happening in the artemis client api.  Or is it simply that the JMSManagement api is left aside?

We are planning to migrate all our brokers to version 2.0 in the next months, so we'll probably give JTB a try then.

Meanwhile, we'd like to thank you for your time and wish you the best!

David

**Comment by titou10titou10** [comment]
Glad we found the problem.Your server does not act as a JMS server. Maybe you could start a JMS server instance instead of the core one as the JMS server is a super set of the core one and add a JMS facade to the core. That's it.. It is not surprising it is working for you as jms objects are  just wrapper to cord  queue or address. Maybe you could close this issue.Thanks

**Comment by raddave** [comment]
Issue closed.  thanks.
