### ISSUE TITLE
connect to Artemis without "manage"?

### ISSUE THREAD

**Issue by sorin-costea** [jmstoolbox/jmstoolbox#63]
## Specifications
- JMSToolBox version: 5.5.0
- OS (Name, version, 32/64bits): Win x64
- Q provider (kind, version) : Artemix 1.x

## Expected Behavior
I don't need to list all existing queues or create ones or anything else management-related, just browse a known existing queue (and if I'm lucky even send/consume from it).

## Actual Behavior
If my user doesn't have "manage" right I cannot even connect, getting the ActiveMQSecurityException that my user doesn't have permission='CREATE_NON_DURABLE_QUEUE' for queue jms.tempqueue...

## Steps to Reproduce the Problem

  1. create Artemis session following the steps in Wiki section 2.6
  2. no idea what a broker.xml file is, never seen one
  3. I configure the user roles in standalone-full.xml of my EAP 7.1.5, but without a "manage" role
  4. bang connection fails with AMQ22913

**Comment by titou10titou10** [comment]
As explained (maybe badly) in the wiki, the change in`"broker.xml"`is not for instance of Artemis 1.x embedded with JBoss . For those, there is a dedicated session farther on the page, as you've seen it       

As said in the WiKi "_the user that will connect to the messaging engine **must** have the "manage" permission._" so it is If you not set this permission, JMSToolBox will not work    

The current whole philosphy around JMSToolBox is that the list of destinations if fetched from the Queue Manger itself and not from an aribtrary list set somewhere

**Comment by sorin-costea** [comment]
Got it, thank you!
