### ISSUE TITLE
Queue browsers with number of messages

### ISSUE THREAD

**Issue by assimbly** [jmstoolbox/jmstoolbox#64]
## Feature request

Currently, when connected to a broker. There is a list of brokers. You can see the number of messages only for a single queue when the user clicks on that queue. 

I would like to have a view where there is column with all queues and a column with the number of messages (updated/refresh at an interval. For example every 3 seconds).

Similar to http://queuemanager.nl/messagemanager-win32.png (You can test this functionality with ActiveMQ Classic and Message Manager as a client).

This function is especially useful for the maintainers of brokers as they can see at a glance what's going on.

**Comment by titou10titou10** [comment]
Did you tried the "Queues depth" vue? 
You can display it by either double clicking on the "Queues" tree label in the Session explorer on the left or perform a right click on the session name and then "Show Queues depth"
Is that what you are looking for?

**Comment by assimbly** [comment]
Yes that's exactly what I was looking for. I was however confused, because sometimes "Show Queues Depth" is available when right-clicking queues and sometimes not. See screenshots:

![QueueDepthsAvailable](https://user-images.githubusercontent.com/35961736/69266005-9b98c080-0bca-11ea-8cfa-77135bf9e7a5.JPG)
![QueueDepthsNotAvailable](https://user-images.githubusercontent.com/35961736/69266006-9b98c080-0bca-11ea-8c22-dfbc9cee75b9.JPG)

Is it also possible (a setting?) to start Queue Depth browser on startup with auto refresh turned on?

**Comment by titou10titou10** [comment]
OK
Could you please open an issue regarding the problem of the menu that does not show as it should?
I'll try to find some time to investigate later
As for your question, no it is not possible to open JMSToolBox, open a session, show the Queue depth view with auto refresh on at thtis time
