### ISSUE TITLE
Context Menu doesn't always Show Queues depth

### ISSUE THREAD

**Issue by assimbly** [jmstoolbox/jmstoolbox#65]
## Specifications
- JMSToolBox version: 5.5.0
- OS (Name, version, 32/64bits): 64biys
- Q provider (kind, version) : ActiveMQ Artemis 2.10.0

## Expected Behavior

"Show Queues depth" should be visible when there is session with a Wueues folder. When the user right-clicks on the Queues folder this option should be available.

## Actual Behavior

Sometimes this menu option is available, sometimes not.

See also screenshots: https://github.com/jmstoolbox/jmstoolbox/issues/64

## Steps to Reproduce the Problem

  1. Open a session
  2. Right-click on "Queues" folder
  3. Perform some other actions (for example open queues)
  4. Right-click on "Queues" folder again

## Logs
Eventually, attach the log files which are `"<user>\.jtb\JMSToolBox\jmstoolbox.log"` and `"<user>\.jtb\.metadata\.log"`    
They can be exported directly from JMStoolBox: Menu "Help" > "Export JMSToolBox log files..."

**Comment by titou10titou10** [comment]
Thanks for reporting
The probem arises when you select a tree object in the left browser that is not a session nor the "Queues" folder. After that, the menu will never appear...
It is fixed in the coming v5.6.0 version
