### ISSUE TITLE
Linux releases won't start

### ISSUE THREAD

**Issue by kec24** [jmstoolbox/jmstoolbox#67]
## Specifications
- JMSToolBox version: 5.6.0
- OS (Name, version, 32/64bits): Linux 64bit
- Q provider (kind, version) : ActiveMQ

## Expected Behavior
UI to open when executing "JMSToolbox" binary.

## Actual Behavior
Error message window and NPE stacktrace on console.

## Steps to Reproduce the Problem
  1. Download JMSToolbox release for Linux
  2. Execute JMSToolbox

## Logs
[1578641854214.log](https://github.com/jmstoolbox/jmstoolbox/files/4044422/1578641854214.log)

**Comment by titou10titou10** [comment]
The logs show that JMSToolBox has been started with Java 1.8
JMSToolBox requires Java 11 since v5.0.0
