### ISSUE TITLE
Error connect to OpenLiberty with restconnector ssl

### ISSUE THREAD

**Issue by sercheo87** [jmstoolbox/jmstoolbox#71]
## Specifications
- JMSToolBox version: 5.6.0
- OS (Name, version, 32/64bits): Windows 10PRO
- Q provider (kind, version) : Open Liberty 20.0.0.1

## Expected Behavior
Connect by service:jmx:rest://aaba0e32da65:10502/IBMJMXConnectorREST

Open Liberty run in container with expose ports Connector rest and http default

## Actual Behavior
Connect JMSToolbox by SSL

[JTB_20203114_0802671_eclipse.log](https://github.com/jmstoolbox/jmstoolbox/files/4204681/JTB_20203114_0802671_eclipse.log)
[JTB_20203114_0802671_jmstoolbox.log](https://github.com/jmstoolbox/jmstoolbox/files/4204682/JTB_20203114_0802671_jmstoolbox.log)

## Logs
Eventually, attach the log files which are `"<user>\.jtb\JMSToolBox\jmstoolbox.log"` and `"<user>\.jtb\.metadata\.log"`    
They can be exported directly from JMStoolBox: Menu "Help" > "Export JMSToolBox log files..."

**Comment by titou10titou10** [comment]
Did you follow the instructions to setup the connection on here? https://github.com/jmstoolbox/jmstoolbox/wiki/2.2-Setup-for-IBM-LibertyProfile
Also in some of your tests, it seems that the certificate is unknown to JTB. You can disable certificates validity checking in the preferences

**Comment by sercheo87** [comment]
Thanks, adding jar of WAS connection was successfully.
