### ISSUE TITLE
SSL problem with version 5 (or OpenJDK 11?)

### ISSUE THREAD

**Issue by sburkard** [jmstoolbox/jmstoolbox#72]
## Specifications
- JMSToolBox version: 5.5.0
- OS (Name, version, 32/64bits): Windows 10 64bit
- Q provider (kind, version) : ActiveMQ 5.13.4

## Expected Behavior
With JMSToolBox 4.11.0 (that contained Oracle JDK 8) I was able to connect with mutual SSL to my ActiveMQ brokers. I have configured key store and truststore on the connection and it worked fine. 

## Actual Behavior
Recently I downloaded version 5.5 of JMSToolBox and applied the same configuration as for the older version. In fact most of it was applied automatically because the settings file in the `userhome\.jtb` folder is shared between both versions.

I can still start JMSToolBox 4.11.0 and connect to the brokers. When I quit it and start version 5.5 it fails to connect to the broker (same key and trustmaterial). 

I noticed in the release notes that the newer versions use OpenJDK 11.x. But I did not found fundamental things that changed regarding SSL. 

However, I tried to activate debug logging with `-Djavax.net.debug=ssl` in the `JMSToolBox.ini`, but it seems to be ignored, there is the same logging as without it.

How can I activate debug logging for the SSL connection in JMSToolbox to track down this problem? 

## Logs
    2020-02-24 14:19:41:124 INFO  [o.t.j.q.a.ActiveMQQManager  ] connecting to [brokername] - JMSToolBox-1582550365864
    2020-02-24 14:19:41:127 DEBUG [o.t.j.q.a.ActiveMQQManager  ] Trying JMX connection with URL 'service:jmx:rmi:///jndi/rmi://[host]:[port]/jmxrmi'
    2020-02-24 14:19:41:532 WARN  [o.t.j.q.a.ActiveMQQManager  ] Connection failed: error during JRMP connection establishment; nested exception is: 
    	javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    2020-02-24 14:19:41:542 ERROR [o.t.j.u.JTBStatusReporter   ] Connect unsuccessful
    java.lang.Exception: Failed to connect to a 'master' ActiveMQ broker with the information set in the session definition

**Comment by sburkard** [comment]
OK, I just tried the same with version 4.14.0 which is already using OpenJDK, but still version 8 and it doesn't work either. 

But with this version, the error message is much more clear: that the certificate host name does not match. This is totally true because we have a single cert for all non-production-brokers to simplify things. With the old JDKs this worked fine.

To get around this the JMS Toolbox would have to implement a HostnameVerifier that accepts all names and offers to activate it in the preferences. Therefore I close this ticket.

**Comment by titou10titou10** [comment]
JMSToolBox already has a preference to bypass certificate check. 
Did you tried it?
Were you able to connect with this option activated?

**Comment by sburkard** [comment]
Yes I tried this option, but it didn't work. It just makes that the client
does not need to have the trust Material and behaves as it would have it.

My problem is that the server sends a certificate that doesn't match the
servers hostname.

If you want the client to accept this you have to implement a
hostnameverifier

**Comment by titou10titou10** [comment]
That's weird, because if you check the option to disable the certificate check in the preference, it  also disable the hostname verification. In [org.titou10.jtb/config.ConfigManager](https://github.com/jmstoolbox/jmstoolbox/blob/dev/org.titou10.jtb.core/src/org/titou10/jtb/config/ConfigManager.java) :

    private void relaxSSLSecurityIfRequired(JTBStatusReporter jtbStatusReporter) {
        {...}
            // Disable Host Name verification
            HttpsURLConnection.setDefaultSSLSocketFactory(ctx.getSocketFactory());
            HostnameVerifier allHostsValid = new HostnameVerifier() {
               public boolean verify(String hostname, SSLSession session) {
                  return true;
               }
            };
            HttpsURLConnection.setDefaultHostnameVerifier(allHostsValid);

In the next version I will replace`X509TrustManager`by`X509ExtendedTrustManager` for the `"TrustEverythingSSLTrustManager"`class as it should fix all hostname verification problems

**Comment by titou10titou10** [comment]
I just pushed the fix in order to use the `X509ExtendedTrustManager` class

**Comment by sburkard** [comment]
OK since you also handle hostname verification with the "trust all" checkbox, I rechecked this whole thing and the results are 

**Version 4.11.0**

* without "trust all"
  * works fine
* with "trust all"
  * `javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate` (GUI and Log)
  * I am quite confused about this one!

**Version 4.13.0**

* without "trust all"
  * `java.security.cert.CertificateException: No name matching xa1465.visana.ch found` (GUI and Log)
* with "trust all"
  * `java.security.cert.CertificateException: No name matching xa1465.visana.ch found` (GUI and Log)
* Sounds like hostname verification problem. Was hostname verification already in place in this version?

**Version 4.14.0**

* without "trust all"
  * `java.security.cert.CertificateException: No name matching xa1465.visana.ch found` (GUI and Log)
* with "trust all"
  * `java.security.cert.CertificateException: No name matching xa1465.visana.ch found` (GUI and Log)
* Sounds like hostname verification problem. Was hostname verification already in place in this version?

**Version 5.5.0**

* without "trust all"
  * Exception: failed to connect to a 'master' ActiveMQ broker ... (GUI)
  * `javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target` (Log)
* with "trust all"
  * `java.net.SocketException: Connection or outbound has closed` (GUI and Log)

**Comment by titou10titou10** [comment]
Thanks for your analysis!
- the hostname verification bypass has been there before v4.11.0
- a change between v4.11.0 and 4.13.0 is the upgrade of the embedded JRE to 1.8.0._19.  v4.11.0 was using JRE 1.8.0._181
- what is strange is that we use the bypass on here with self signed certs or private CA and we don't have issues with it. There must be something different in your CA or certificate that make JTB fail

The change I commit yesterday (ie use`X509ExtendedTrustManager`instead of `X509TrustManager`is based on many posts found on stackoverflow like this one :
https://stackoverflow.com/questions/52115699/relaxing-ssl-algorithm-constrains-programmatically/52165311#52165311
