### ISSUE TITLE
Can't connect to IBM MQ Server with 9.1.4.0 allclient

### ISSUE THREAD

**Issue by thuri** [jmstoolbox/jmstoolbox#75]
## Specifications
- JMSToolBox version: 4.1.0, 5.6.0
- OS (Name, version, 32/64bits): Windows 64 bit
- Q provider (kind, version) : IBM MQ 9.x

## Expected Behavior
JMS Toolbox should be able to connect to the Queuemanager when using mqallclient 9.1.4.0 

## Actual Behavior

![image](https://user-images.githubusercontent.com/1602552/77891464-499b3200-7271-11ea-95a6-5ccf1fe360c6.png)

Error message when trying to connect (see Screenshot), which reads (translated to english):
"The remote channel 'DMS.CLIENT' on Host '' is currently not available"

What seems strange here is that the host value is displayed as an empty string. IBM may have changed how the connection is to be established. 
Perhaps some Property namens have changed 
https://developer.ibm.com/messaging/learn-mq/mq-tutorials/develop-mq-jms/ 

## Steps to Reproduce the Problem

  1. Download the 9.1.4.0 libs from [maven central](https://search.maven.org/artifact/com.ibm.mq/com.ibm.mq.allclient) (Carefull: Version 9.1.0.4 is working) 
  1. Use the libs for the Q Manager "IBM MQ"
  1. Create a Session using the above Q Manager (we're using user/password authentication). Channel can be SYSTEM.ADMIN.SVRCONN or probably something differently (Currently not able to try another one because of issue with authorization; but that's not related to this issue as same config is working with 9.1.0.4 version of the lib)

## Logs
[jmstoolbox.log](https://github.com/jmstoolbox/jmstoolbox/files/4401583/jmstoolbox.log)

**Comment by titou10titou10** [comment]
It works for me with v9.1.3.0 and v9.1.4.0 of`com.ibm.mq.allclient jar`
What is the exact version of your MQ Server? do you have messages in the server logs?
Is the listener for channel`SYSTEM.ADMIN.SVRCONN` up and  running on your server?
Did you follow the ionstruction on here: https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.1.0/com.ibm.mq.explorer.doc/e_gui_remote_enabling_default.htm

**Comment by thuri** [comment]
I asked the admin about the server logs and i hope i'll get them today.

The thing is, that i can connect with the same settings (regardless which channel) with the 9.1.0.4 version of the lib. 

There are no stupid questions :-) But yes, host, port and channel are set correclty. Also the channel and the queuemanager. I actually only change the lib in the Q Manager and connections stop working (after the restart)

**Comment by thuri** [comment]
Got the logs (see below; needed to mask IPs, usernames etc with # signs)

Found that the client seems to sent my windows user name to the server when trying to craete the MQQueueManager instance. And the server doesn't like that.

```
30.03.2020 13:36:41 - Process(17506.13) User(mqm) Program(amqrmppa)
                    Host(##########) Installation(Installation1)
                    VRMF(9.0.0.4) QMgr(MQ_DEV)
                   
AMQ9777: Channel was blocked

EXPLANATION:
The inbound channel 'SYSTEM.ADMIN.SVRCONN' was blocked from address
'##.###.###.##' because the active values of the channel matched a record
configured with USERSRC(NOACCESS). The active values of the channel were
'CLNTUSER(########)'.
ACTION:
Contact the systems administrator, who should examine the channel
authentication records to ensure that the correct settings have been
configured. The ALTER QMGR CHLAUTH switch is used to control whether channel
authentication records are used. The command DISPLAY CHLAUTH can be used to
query the channel authentication records.
```

**Comment by titou10titou10** [comment]
Do you set the user/password on the JTB session? If so, is it the user you see in the server logs?
Are your authorized to connect via this channel from that IP address?
At some point MQ changed the way it handles connection without a userid

**Comment by thuri** [comment]
the user is set in the JTB session but it is NOT the userid in the log (which is  my windows user name). Somehow it's loosing or ignoring the settings. 

Probably it's just a verison mismatch problem as the server is a 9.0.0.4 and the libs are 9.1.x
But than IBM must have changed something between 9.1.0.x and 9.1.3.0 

Authorization is granted as the connection is working with the exaclty same session config with the 9.1.0.4

**Comment by titou10titou10** [comment]
The fixes for MQ v9.1 per FP are here (for the server and the client) https://www.ibm.com/support/pages/fix-list-ibm-mq-version-91x-continuous-delivery
Maybe you could find something in there, it may also be a bug in the v9.1.0.4 client. As said before it is working on my test system

**Comment by thuri** [comment]
Thanks for the links. The problem is introduced with 9.1.2.0 of the all client. 9.1.1.0 is the last version that is still working.

https://www.ibm.com/support/pages/node/4762695 may be the source of the issue.

At https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.1.0/com.ibm.mq.pro.doc/q132440_.htm IBM lists changed functions and resources in 9.1.2. and it looks like they changed something regarding the  MQCNO_RECONNECT_Q_MGR parameters. But whether that change has something to do with our issue, i don't know.

**Comment by thuri** [comment]
I guess the issue we're experiencing ist actually IT25839 (the first link in the previous comment). But we're actually not capable of determining whether all preconditions ot that issue actually satisfied. 

Therefore i'll close this issue and thank @titou10titou10  very much for the discussion.
And thank you even more for JMS Toolbox, as it is exactly the tool I need.
