### ISSUE TITLE
Error when importing payload with Bytes type

### ISSUE THREAD

**Issue by Zavirak** [jmstoolbox/jmstoolbox#82]
## Specifications
- JMSToolBox version: 5.6.0
- OS (Name, version, 32/64bits): W10 64-bit
- Q provider (kind, version) : IBM MQ 8.0.0

## Expected Behavior
Import txt file as a payload of a Bytes type to a template or  a message

## Actual Behavior
After importing a .txt file the 72th character of the payload it is not correctly encoded - there is "??" in its position

## Steps to Reproduce the Problem

1. Open a new message pop-up within a queue window pane
2. Select |Payload| tab
3. Select "Type"=Bytes
4. Click on [Import...]
5. If there are more than 71 bytes in the imported file, the 72th byte is displayed as "??".

## Logs

[hexDecTest.txt](https://github.com/jmstoolbox/jmstoolbox/files/4729424/hexDecTest.txt)
[jmstoolbox.log](https://github.com/jmstoolbox/jmstoolbox/files/4729427/jmstoolbox.log)
[.log](https://github.com/jmstoolbox/jmstoolbox/files/4729431/default.log)

Eventually, attach the log files which are `"<user>\.jtb\JMSToolBox\jmstoolbox.log"` and `"<user>\.jtb\.metadata\.log"`    
They can be exported directly from JMStoolBox: Menu "Help" > "Export JMSToolBox log files..."

**Comment by titou10titou10** [comment]
Weird.. It works for me with with your file (MQ too)

**Comment by titou10titou10** [comment]
Closing this issue because it has not had recent activity
Please fell free to re-open it you have more information
