### ISSUE TITLE
Payload (JSON: Format JSON files when viewing messages in a JMS endpoint

### ISSUE THREAD

**Issue by assimbly** [jmstoolbox/jmstoolbox#84]
## Specifications
- JMSToolBox version: 5.7.0
- OS (Name, version, 32/64bits): 64
- Q provider (kind, version) : ActiveMQ

## Expected Behavior

Currently, when sending a XML or JSON message, the message can be formatted. In the queue viewer there is however only a tab for Payload (XML) and not yet for Payload (JSON)

**Comment by titou10titou10** [comment]
You mean in the message browser on the bottom right of the window, right?

**Comment by assimbly** [comment]
"You mean in the message browser on the bottom right of the window, right?" 

Yes

**Comment by assimbly** [comment]
Great!
