### ISSUE TITLE
Support the ActiveMQ in wildfly as a queue provider

### ISSUE THREAD

**Issue by marlowa** [jmstoolbox/jmstoolbox#86]
## Specifications
- JMSToolBox version: 5.8.0
- OS (Name, version, 32/64bits):Windows and Linux
- Q provider (kind, version) : activeMQ/wildfly

## Expected Behavior
Explicit support of this configuration.

## Actual Behavior
It supports the old JBoss AS with Hornet. JBoss-AS has been superseded by wildfly and wildfly moved from Hornet to ActiveMQ some time ago.

**Comment by titou10titou10** [comment]
JMSToolBox support Wildfly since  a while bujt I didn't test it with the latests version of Wildfly. 
Did you follow instructions as described in the WiKi here: https://github.com/jmstoolbox/jmstoolbox/wiki/2.6-Setup-for-Apache-Artemis

If so, what problem did you encountered?

**Comment by titou10titou10** [comment]
Closing this issue because it has not had recent activity
Please fell free to re-open it you have more information
