### ISSUE TITLE
jmstoolbox as docker container

### ISSUE THREAD

**Issue by abennani31** [jmstoolbox/jmstoolbox#89]
## Specifications
- JMSToolBox version:
- OS (Name, version, 32/64bits):
- Q provider (kind, version) :

## Expected Behavior
it possible to run jmstoolbox as a docker container?

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Logs
Eventually, attach the log files which are `"<user>\.jtb\JMSToolBox\jmstoolbox.log"` and `"<user>\.jtb\.metadata\.log"`    
They can be exported directly from JMStoolBox: Menu "Help" > "Export JMSToolBox log files..."

**Comment by titou10titou10** [comment]
The answer is no. JTB is based onf eclipse-rcp
